"""initial schema

Revision ID: 1286f25de7b8
Revises: 
Create Date: 2026-05-27 09:59:37.062493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1286f25de7b8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('keyword_weights',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('term', sa.Text(), nullable=False),
    sa.Column('weight', sa.Float(), server_default=sa.text('0.0'), nullable=False),
    sa.Column('like_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('dislike_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'term')
    )
    op.create_index('idx_keyword_weights_user_id', 'keyword_weights', ['user_id'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('miniflux_feed_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'miniflux_feed_id', name='uq_sources_user_feed')
    )
    op.create_table('articles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('miniflux_entry_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('summary_short', sa.Text(), nullable=True),
    sa.Column('summary_executive', sa.Text(), nullable=True),
    sa.Column('og_image_url', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('enriched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('miniflux_entry_id')
    )
    op.create_index('idx_articles_published_at', 'articles', [sa.literal_column('published_at DESC')], unique=False)
    op.create_index('idx_articles_source_id', 'articles', ['source_id'], unique=False)
    op.create_index('idx_articles_status', 'articles', ['status'], unique=False)
    op.create_table('article_feedbacks',
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("action IN ('like', 'dislike', 'skip', 'save')", name='ck_feedbacks_action'),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'user_id')
    )
    op.create_index('idx_feedbacks_user_id', 'article_feedbacks', ['user_id'], unique=False)
    op.create_table('article_impressions',
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'user_id')
    )
    op.create_index('idx_impressions_user_id', 'article_impressions', ['user_id'], unique=False)
    op.create_table('article_keywords',
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('term', sa.Text(), nullable=False),
    sa.Column('salience', sa.Float(), nullable=False),
    sa.CheckConstraint('salience >= 0.0 AND salience <= 1.0', name='ck_article_keywords_salience'),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'term')
    )
    op.create_index('idx_article_keywords_term', 'article_keywords', ['term'], unique=False)
    op.create_table('article_relevance_scores',
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.CheckConstraint('relevance_score >= 0.0 AND relevance_score <= 1.0', name='ck_relevance_scores_range'),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'user_id')
    )
    op.create_index('idx_relevance_scores_user_id', 'article_relevance_scores', ['user_id', sa.literal_column('relevance_score DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_relevance_scores_user_id', table_name='article_relevance_scores')
    op.drop_table('article_relevance_scores')
    op.drop_index('idx_article_keywords_term', table_name='article_keywords')
    op.drop_table('article_keywords')
    op.drop_index('idx_impressions_user_id', table_name='article_impressions')
    op.drop_table('article_impressions')
    op.drop_index('idx_feedbacks_user_id', table_name='article_feedbacks')
    op.drop_table('article_feedbacks')
    op.drop_index('idx_articles_status', table_name='articles')
    op.drop_index('idx_articles_source_id', table_name='articles')
    op.drop_index('idx_articles_published_at', table_name='articles')
    op.drop_table('articles')
    op.drop_table('sources')
    op.drop_index('idx_keyword_weights_user_id', table_name='keyword_weights')
    op.drop_table('keyword_weights')
    op.drop_table('users')
    # ### end Alembic commands ###
